    var distritos=[
    " de mayo",
    " de julio",
    "adolfo alsina",
    "alberti",
    "almirante brown",
    "arrecifes",
    "avellaneda",
    "ayacucho",
    "azul",
    "bahia blanca",
    "balcarce",
    "baradero",
    "benito juarez",
    "berazategui",
    "berisso",
    "bolivar",
    "bragado",
    "brandsen",
    "campana",
    "capitan sarmiento",
    "carlos casares",
    "carlos tejedor",
    "carmen de areco",
    "castelli",
    "ca�uelas",
    "chacabuco",
    "chascomus",
    "chivilcoy",
    "colon",
    "coronel dorrego",
    "coronel pringles",
    "coronel rosales",
    "coronel suarez",
    "daireaux",
    "dolores",
    "ensenada",
    "escobar",
    "esteban echeverria",
    "exaltacion de la cruz",
    "ezeiza",
    "florencio varela",
    "florentino ameghino",
    "general alvarado",
    "general alvear",
    "general arenales",
    "general belgrano",
    "general guido",
    "general la madrid",
    "general las heras",
    "general lavalle",
    "general madariaga",
    "general paz",
    "general pinto",
    "general pueyrredon",
    "general rodriguez",
    "general san martin",
    "general viamonte",
    "general villegas",
    "gonzales chaves",
    "guamini",
    "hipolito irigoyen",
    "hurlingham",
    "ituzaingo",
    "jose c. paz",
    "junin",
    "la matanza",
    "la plata",
    "lanus",
    "laprida",
    "las flores",
    "leandro n alem",
    "lezama",
    "lincoln",
    "loberia",
    "lobos",
    "lomas de zamora",
    "lujan",
    "magdalena",
    "maipu",
    "malvinas argentinas",
    "mar chiquita",
    "marcos paz",
    "mercedes",
    "merlo",
    "monte",
    "monte hermoso",
    "moreno",
    "moron",
    "navarro",
    "necochea",
    "olavarria",
    "partido de la costa",
    "patagones",
    "pehuajo",
    "pellegrini",
    "pergamino",
    "pila",
    "pilar",
    "pinamar",
    "presidente peron",
    "puan",
    "punta indio",
    "quilmes",
    "ramallo",
    "rauch",
    "rivadavia",
    "rojas",
    "roque perez",
    "saavedra",
    "saladillo",
    "salliquelo",
    "salto",
    "san  andres de giles",
    "san  antonio de areco",
    "san cayetano",
    "san fernando",
    "san isidro",
    "san miguel",
    "san nicolas",
    "san pedro",
    "san vicente",
    "suipacha",
    "tandil",
    "tapalque",
    "tigre",
    "tordillo",
    "tornquist",
    "trenque lauquen",
    "tres arroyos",
    "tres de febrero",
    "tres lomas",
    "vicente lopez",
    "villa gesell",
    "villarino",
    "zarate"]





    let niveles=[
        "adultos",
        "adultos y cens",
        "artistica",
        "educacion fisica",
        "especial",
        "inicial",
        "primaria",
        "psicologia",
        "secundaria",
        "secundaria adultos",
        "superior",
        "tecnico profesional"]

                let cargos=[
                  "abordaje de la interpretacion ydi",
                  "actuacion a.c",
                  "actuacion ctu",
                  "actuacion ytu",
                  "actuacion y procedimiento constructivos en teatro yoc",
                  "actuaci�n y procedimientos constructivos en teatro poc",
                  "adaptacines curriculares visuales dv",
                  "adaptaciones curriculares auditivas du",
                  "adaptaciones curriculares intelectuales di",
                  "adaptaciones curriculares intelectuales di",
                  "adaptaciones curriculares neurolocomotoras de",
                  "administracion a.d",
                  "administraci�n y gesti�n de los recursos humanos  arh",
                  "agroalimentos aga",
                  "agropecuaria a.g",
                  "algoritmos y estructuras de datos  i  y  ii aes",
                  "algoritmos y estructuras de datos i, ii t.i.p.p. -l",
                  "alimentos a.l",
                  "ambiente, desarrollo y sociedad ads",
                  "analisis coreografico yor",
                  "analisis del lenguaje teatral yea",
                  "analisis y produccion en musica yem",
                  "antropologia a.n",
                  "antropologia general an",
                  "antropologia y cultura an",
                  "an�lisis coreogr�fico cor",
                  "an�lisis de modelos circuitales moc",
                  "an�lisis de producci�n en m�sica pem",
                  "an�lisis del lenguaje teatral tea",
                  "an�lisis e interpretaci�n de estados contables aec",
                  "an�lisis matem�tico am",
                  "aplicaciones de electr�nica anal�gica aea",
                  "aplicaciones de electr�nica digital aed",
                  "area administracion /a",
                  "area administracion /e",
                  "area administracion cens - adultos +a",
                  "area alimentacion /c",
                  "area antropologia cens - adultos +g",
                  "area ciencias biologicas /a",
                  "area ciencias biologicas cens - adultos +a",
                  "area ciencias de la educacion /n",
                  "area ciencias de la educacion cens - adultos +o",
                  "area ciencias politicas y juridicas /u",
                  "area ciencias politicas y juridicas /w",
                  "area ciencias politicas y juridicas /y",
                  "area ciencias politicas y juridicas /z",
                  "area comunicacion cens - adultos +e",
                  "area comunicacion social /d",
                  "area contabilidad /r",
                  "area contabilidad /s",
                  "area contabilidad cens - adultos +r",
                  "area cs.politicas y juridicas cens - adultos +u",
                  "area dibujo tecnico /l",
                  "area dibujo tecnico cens - adultos +l",
                  "area ecologia cens - adultos +e",
                  "area economia /g",
                  "area economia /h",
                  "area economia /i",
                  "area economia cens - adultos +g",
                  "area electricidad /o",
                  "area electricidad-cens-adultos +o",
                  "area estetica cens - adultos +n",
                  "area filosofia /p",
                  "area filosofia cens - adultos +p",
                  "area fisica /w",
                  "area fisica /x",
                  "area fisica cens - adultos +x",
                  "area geografia /v",
                  "area geografia cens - adultos +v",
                  "area higiene y seguridad cens - adultos +d",
                  "area historia /w",
                  "area historia cens - adultos +w",
                  "area informatica /z",
                  "area informatica /a",
                  "area informatica cens - adultos +z",
                  "area ingles � y � ciclo egb adultos +ia",
                  "area ingles cens - adultos +f",
                  "area ingles de la educacion general basica-egb /ai",
                  "area lengua extranjera - ingles /f",
                  "area lengua y literatura /b",
                  "area lengua y literatura cens - adultos +b",
                  "area madera /p",
                  "area matematica /i",
                  "area matematica /j",
                  "area matematica cens - adultos +i",
                  "area medicina /o",
                  "area medicina cens - adultos +o",
                  "area musica /p",
                  "area organizacion industrial cens - adultos +n",
                  "area psicologia cens - adultos +s",
                  "area quimica /y",
                  "area quimica /z",
                  "area quimica /a",
                  "area quimica cens - adultos +y",
                  "area sociologia /w",
                  "area sociologia cens - adultos +w",
                  "area teatro ciclo medio y formacion basica *o",
                  "area tecnologia cens - adultos +d",
                  "area turismo /y",
                  "area turismo cens - adultos +a",
                  "areas de centro de produccion total cpt",
                  "arte leng. compl. de la danza artes visuales cd",
                  "arte leng. compl. de la danza m�sica cd",
                  "arte leng. compl. de la danza teatro cd",
                  "arte leng. compl. de la lit. artes visuales cl",
                  "arte leng. compl. de la lit. danza cl",
                  "arte leng. compl. de la lit. m�sica cl",
                  "arte leng. compl. de la literatura teatro cl",
                  "arte leng. compl. de la m�sica artes visuales cm",
                  "arte leng. compl. de la m�sica danza cm",
                  "arte leng. compl. de la m�sica teatro cm",
                  "arte leng. compl. de las artes visuales danza ca",
                  "arte leng. compl. de las artes visuales m�sica ca",
                  "arte leng. compl. de las artes visuales teatro ca",
                  "arte leng. compl. del  teatro danza ct",
                  "arte leng. compl. del teatro artes visuales ct",
                  "arte leng. compl. del teatro m�sica ct",
                  "arte rte",
                  "arte-lenguaje complementario  improvisacion y composicion coreografica ylc",
                  "asistencia sobre la utilizaci�n de aplicaciones generales aag",
                  "asistente educacional *ae",
                  "asistente social *as",
                  "astronomia a.s",
                  "auditoria y control de gesti�n aud",
                  "ayudante del area danzas clasicas aa",
                  "ayudante del area musica en danza clasica ma",
                  "ayudante del area musica-canto ak",
                  "ayudante del area musica-iniciacion aa",
                  "ayudante del area musica-practica de conjunto ab",
                  "ayudante del area plastica-ceramica ad",
                  "ayudante del area plastica-dibujo af",
                  "ayudante del area plastica-dibujo al",
                  "ayudante del area plastica-escultura ac",
                  "ayudante del area plastica-escultura ai",
                  "ayudante del area plastica-grabado ab",
                  "ayudante del area plastica-grafica ah",
                  "ayudante del area plastica-pintura aa",
                  "ayudante del area plastica-pintura ag",
                  "ayudante del area teatro aa",
                  "ayudante t�cnico pedag�gico en artes visuales ylv",
                  "ayudante t�cnico pedag�gico en inform�tica yli",
                  "ayudante t�cnico pedag�gico en qu�mica yqq",
                  "bases de datos bdd",
                  "bibliotecario /bi",
                  "bibliotecario /bp",
                  "bibliotecario bla",
                  "bibliotecario de cie bie",
                  "bibliotecario institutos terciarios artistica bli",
                  "bibliotecologia b.b",
                  "biologia b.g",
                  "biologia blg",
                  "biologia y su ense�anza b.p",
                  "biolog�a, gen�tica y sociedad bgs",
                  "bioquimica b.q",
                  "c.e. administracion jap",
                  "c.e. administracion joa",
                  "c.e. administracion de personal jdp",
                  "c.e. antropologia socio-cultural jas",
                  "c.e. comunicacion jcm",
                  "c.e. contabilidad jco",
                  "c.e. contabilidad practica jpr",
                  "c.e. cs. biologicas jcb",
                  "c.e. cs. biologicas medicina jes",
                  "c.e. cs. politicas y juridicas jcp",
                  "c.e. cs. politicas y juridicas jde",
                  "c.e. cs. politicas y juridicas jec",
                  "c.e. cs. politicas y juridicas jli",
                  "c.e. derecho comercial y laboral jdc",
                  "c.e. diagramacion y logica jdl",
                  "c.e. economia jea",
                  "c.e. economia jep",
                  "c.e. filosofia jfl",
                  "c.e. fisica jfi",
                  "c.e. geografia jge",
                  "c.e. historia jhi",
                  "c.e. historia-geografia jhg",
                  "c.e. informatica jif",
                  "c.e. ingl?es t?ecnico  jit",
                  "c.e. ingles jin",
                  "c.e. introduccion a la computacion jic",
                  "c.e. introduccion a las ciencias experimentales jie",
                  "c.e. laboratorio de manejo de programas utilitarios jlm",
                  "c.e. lengua y literatura jll",
                  "c.e. maestro bibliotecario jmb",
                  "c.e. maestro de ciclo jcl",
                  "c.e. matematica jma",
                  "c.e. mecanografia jme",
                  "c.e. nociones de administracion de empresas jna",
                  "c.e. nociones de derecho  jno",
                  "c.e. nociones de derecho y legislacion laboral jnd",
                  "c.e. nociones preliminares de finanzas jnp",
                  "c.e. organizaci�n administrativa jor",
                  "c.e. practicas de derecho jpd",
                  "c.e. preceptor jpk",
                  "c.e. preceptor jpq",
                  "c.e. principios de administraci�n de empresas jpa",
                  "c.e. probl. social contempor�nea jhp",
                  "c.e. psicologia jsi",
                  "c.e. quimica jqu",
                  "c.e. sociologia jrh",
                  "c.e. sociologia jso",
                  "c.e. sociologia de la educacion jms",
                  "c.e. taller de est?tica jte",
                  "c.e. taller de est?tica jte",
                  "c.e. taller de t?cnicas de estudio y expresion  jtt",
                  "c.e. taller de t?ecnicas de trabajo social jcs",
                  "c.e. taller de te?cnicas de la comunicacion social jtc",
                  "c.e. tecnologia jba",
                  "c.e. tecnologia jts",
                  "c.e. teoria, legislacion y procedimientos impositivos jtl",
                  "canto colectivo yco",
                  "canto coral ycn",
                  "canto popular ycr",
                  "capital humano y relaciones laborales chr",
                  "centrales el�ctricas cen",
                  "cereales cer",
                  "ciencias de la educacion c.e",
                  "ciencias de la tierra cdt",
                  "ciencias naturales cnt",
                  "ciencias politicas c.p",
                  "ciencias politicas y su ense�anza c.d",
                  "ciencias sociales csc",
                  "combusti�n de los motores endot�rmicos moe",
                  "comercializacion c.o",
                  "comercializacion com",
                  "comercio exterior c.x",
                  "comerializaci�n de empresas tur�sticas y hoteleras cet",
                  "comportamiento de las estructuras cde",
                  "composicion musical grupal  ylm",
                  "comunicacion social c.s",
                  "comunicaci�n y culturas del consumo cyc",
                  "comunicaci�n y transf. socioculturales siglo xxi cyt",
                  "comunicaci�n, cultura y sociedad ccs",
                  "conocimiento de los materiales m. mayor de obras cmm",
                  "conocimiento de los materiales t�c. automotores cma",
                  "conocimiento de los materiales t�c. electromec. cme",
                  "construccion de ciudadania ccd",
                  "contables c.b",
                  "costos cos",
                  "cultura y esteticas contemporaneas -h",
                  "danza adz",
                  "danza clasica *a",
                  "danza clasica i, ii, iii y iv ycl",
                  "danza contemporanea i, ii, iii y iv yct",
                  "danza folklorica y popular i, ii, iii, iv y v yfp",
                  "danza moderna *d",
                  "danza-folklore *i",
                  "danza-historia ii *h",
                  "danzas expresion corporal *c",
                  "danzas tradicionales argentinas *b",
                  "derecho der",
                  "derecho administrativo d.d",
                  "derecho civil d.c",
                  "derecho comercial d.m",
                  "derecho del trabajo y seguridad social d.t",
                  "derecho penal d.p",
                  "derechos del trabajo det",
                  "derechos humanos y ciudadania dhc",
                  "desarrollo de aplicaciones web din�micas dwd",
                  "desarrollo de aplicaciones web est�ticas dwe",
                  "desarrollo de programas y manipulaci�n de datos dpd",
                  "destinos turisticos  tdt",
                  "dibujo tecnol�gico maestro mayor de obras dtm",
                  "dibujo tecnol�gico tecnico automotores dta",
                  "dibujo tecnol�gico tecnico electromecanica dte",
                  "didactica y lengua de se�as d.s",
                  "dinamica de grupos pc",
                  "direcci�n de la ejecuci�n de instalaciones dej",
                  "director xxd",
                  "discapacidad intelectual d.i",
                  "dise�o asistido y simulaci�n electr�nica das",
                  "dise�o y gestion de proyectos turisticos sociocomunitarios dgp",
                  "dise�o y gesti�n de proyectos dis",
                  "dise�o y procesamiento mec�nico prm",
                  "dise�o y proyecto i,  ii dpr",
                  "dispositivos de accionamiento y control dac",
                  "docentes acompa�antes primaria iep",
                  "docentes acompa�antes primaria-talleristas iet",
                  "docentes acompa�antes secundaria ies",
                  "documentaci�n t�cnica dot",
                  "ecologia e.g",
                  "economia -g",
                  "economia e.m",
                  "economia social y politica e.i",
                  "economia y su ense�anza e.o",
                  "econom�a eno",
                  "econom�a pol�tica epo",
                  "educacion *a",
                  "educacion fisica e.f",
                  "educacion fisica efc",
                  "educacion fisica y su ense�anza e.d",
                  "educaci�n f�sica y comunidad efu",
                  "educaci�n f�sica y corporeidad fco",
                  "educaci�n f�sica y cultura efi",
                  "ejercico profesional de la construcci�n epc",
                  "electronica computacion e.t",
                  "electrotecnia nia",
                  "electrotecnia del automotor eau",
                  "electrotecnia y electronica t.e.i.e. -k",
                  "electrotecnia y electr�nica eye",
                  "electr�nica aplicada ela",
                  "electr�nica industrial ein",
                  "electr�nica y autotr�nica nic",
                  "elementos de micro y macro econom�a emm",
                  "ematp suelo y  agua esa",
                  "ematp tecnolog�a de la carne etc",
                  "ematp tecnolog�a de la leche etl",
                  "ematp tecnolog�a de los vegetales etv",
                  "empresas e.r",
                  "enc. de medios de apoyo tec-pedag. en c.sociales ecs",
                  "enc.medios apoyo tecnico-pedag.de biologia alb",
                  "enc.medios apoyo tecnico-pedag.de computacion ali",
                  "enc.medios apoyo tecnico-pedag.de contabilidad alc",
                  "enc.medios apoyo tecnico-pedag.de fisica alf",
                  "enc.medios apoyo tecnico-pedag.de quimica alq",
                  "enc.medios apoyo tecnico-pedag.especialidad taller /pa",
                  "encarg. medios apoyo tec. pedag. area informatica pli",
                  "encargado medios apoyo tec-ped. cs fisicas eff",
                  "encargado medios apoyo tec-ped.biologia ebb",
                  "encargado medios apoyo tec-ped.comunic. arte y dis ead",
                  "encargado medios apoyo tec-ped.construc.civiles eco",
                  "encargado medios apoyo tec-ped.econ.y ges.organiza elc",
                  "encargado medios apoyo tec-ped.electronica eel",
                  "encargado medios apoyo tec-ped.inf/comp/e inf.apl. eli",
                  "encargado medios apoyo tec-ped.med/equip/ins.elec. eld",
                  "encargado medios apoyo tec-ped.quimica eqq",
                  "encargadomedios apoyo tec-ped.biologia ebb",
                  "energ�as alternativas eal",
                  "enfermeria e.n",
                  "ens.mont.y mant.equip.e inst.electr.y electron.ttp -z",
                  "ensayos el�ctricos y de m�quinas el�ctricas eem",
                  "ensayos mec�nicos y qu�micos de materiales - maquinado emq",
                  "ensayos qu�micos y f�sicos - qu�micos esq",
                  "equipamiento para an�lisis qu�micos aplicados y control de procesos ecp",
                  "espacio complementario  ceramica ycc",
                  "espacio complementario  dibujo yld",
                  "espacio complementario  escultura  yce",
                  "espacio complementario pintura  yet",
                  "espacio de la especialidad  escultura  yes",
                  "espacio de la especialidad ceramica yec",
                  "espacio de la especialidad grabado  yeg",
                  "espacio de la especialidad pintura  ypi",
                  "espacio de la practica ingles i.p",
                  "espacio de la pr�ctica industrias y procesos i.z",
                  "espacio de profundizacion del aprendizaje epa",
                  "espacios tur�sticos de la argentina eta",
                  "estadistica y probabilidad e.p",
                  "estructuras esr",
                  "estructuras i  y  estructuras ii etr",
                  "estructuras i y estructuras ii m.m.o. -i",
                  "estudios interculturales en ingl�s est",
                  "farmacia f.a",
                  "filosofia *a",
                  "filosofia f.i",
                  "filosofia del derecho f.d",
                  "filosofia y su ense�anza f.h",
                  "filosofico pedagogica f.g",
                  "filosof�a fia",
                  "filosof�a e historia de la ciencia y la tecnolog�a fct",
                  "fines administracion de personal wap",
                  "fines biolog�a wcb",
                  "fines ciencias pol�ticas wcp",
                  "fines comunicaci�n y medios wcm",
                  "fines contabilidad wco",
                  "fines derecho wdd",
                  "fines dise�o y desarrollo de proyectos  esp. � wpd",
                  "fines economia wee",
                  "fines economia aplicada esp. � wea",
                  "fines economia aplicada  esp. � we",
                  "fines econom�a social  esp. � wes",
                  "fines educacion civica wec",
                  "fines estado y nuevos movimientos sociales esp. � wen",
                  "fines estado y pol�ticas p�blicas esp. � wep",
                  "fines filosof�a wfi",
                  "fines fisica wff",
                  "fines historia y geografia whg",
                  "fines inform�tica wif",
                  "fines ingles win",
                  "fines legislacion impositiva wli",
                  "fines lengua y literatura wll",
                  "fines matem�tica wmt",
                  "fines metodolog�a de la investigaci�n wmi",
                  "fines organizaci�n y adm. de empresas woa",
                  "fines planificacion y gestion de emprendimientos esp.� wpg",
                  "fines pol�ticas p�blicas y derechos humanos esp. � wpp",
                  "fines practica contable laboral e impositiva esp.� wpc",
                  "fines problem�tica social contemporanea wps",
                  "fines psicolog�a wpa",
                  "fines quimica wqq",
                  "fines sistema de informacion esp. � wsi",
                  "fines sociolog�a wss",
                  "fisica f.s",
                  "fisica y su ense�anza f.t",
                  "fisico - quimica fqa",
                  "fonoaudiologia f.n",
                  "fonoaudiologo /fo",
                  "forrajes frj",
                  "fortalecimiento de trayectorias educativas inicial mif",
                  "fortalecimiento de trayectorias educativas primaria  mgf",
                  "fotografia yot",
                  "frances f.r",
                  "franc�s fra",
                  "fundamentos de la qu�mica fdq",
                  "fundamentos de los modelos circuitales fmc",
                  "f�sica fis",
                  "f�sica cl�sica y moderna fcm",
                  "ganaderia gnd",
                  "ganaderia de carne gca",
                  "ganader�a de leche gdl",
                  "gastronomia g.a",
                  "genetica genetica y evolucion ge",
                  "genetica y evolucion g.e",
                  "geografia g.f",
                  "geografia ggf",
                  "geografia mundial -t",
                  "geografia y su ense�anza g.p",
                  "geologia g.g",
                  "gestion de los ambitos de desemp.y negoc.t.e.i.e -u",
                  "gestion y produccion grupal escenico ype",
                  "gesti�n comercial gco",
                  "gesti�n de la producci�n ges",
                  "gesti�n de los �mbitos de desempe�o y negocios gad",
                  "gesti�n de proyectos gpr",
                  "gesti�n financiera bancaria y seguros fin",
                  "gesti�n organizacional gor",
                  "grafica tap -w",
                  "granja � y � a�o gra",
                  "guardavidas gu",
                  "historia h.i",
                  "historia htr",
                  "historia americana h.m",
                  "historia argentina h.a",
                  "historia contemporanea h.c",
                  "historia de la danza escenica en argentina yda",
                  "historia de la danza escenica y popular yhd",
                  "historia del arte h.t",
                  "historia y su ense�anza h.e",
                  "huerta hue",
                  "identidad , tradicion y folklore en america latina ytf",
                  "imagen y nuevos medios inm",
                  "imagen y nuevos medios ynm",
                  "imagen y procedimientos constructivos lep",
                  "imagen y procedimientos constructivos yip",
                  "improvisacion escenica yve",
                  "improvisacion yvn",
                  "improvisacion y composicion coreografica ymp",
                  "improvisaci�n y composici�n coreogr�fica imp",
                  "industrias de procesos i.t",
                  "informatica i.f",
                  "informatica aplicada if",
                  "informatica y computacion if",
                  "ingles i.n",
                  "ingles igs",
                  "ingles y su ense�anza i.e",
                  "ingl�s espec�fico ing",
                  "iniciacion a la danza contemporanea yit",
                  "iniciacion a la danza escenica yde",
                  "iniciacion a la danza folklorica y popular ydf",
                  "iniciacion a la produccion coreografica  escenica yic",
                  "iniciacion a la produccion coreografica  ypc",
                  "inst.y config.de sist. oper. y aplic.ttp-tipp -q",
                  "instalaciones  i,  ii int",
                  "instalaciones de baja tensi�n y media tensi�n ibt",
                  "instalaciones el�ctricas ie",
                  "instalaciones industriales iim",
                  "instalaciones industriales ind",
                  "instalaciones sanitarias y de gas isi",
                  "instalaciones y aplicaciones de la energ�a ape",
                  "instalaciones y maquinas el�ctricas imo",
                  "instalaci�n, configuraci�n y mantenimiento de equipos monousuarios icm",
                  "instalaci�n, configuraci�n y mantenimiento de redes inform�ticas imr",
                  "instalaci�n, mantenimiento y reparaci�n de redes inform�ticas iri",
                  "instalaci�n, mantenimiento y reparaci�n de sistemas computacionales imc",
                  "instrumental de medici�n imu",
                  "instrumento  yns",
                  "instrumento piano o guitarra yii",
                  "instrumento complementario ync",
                  "instrumento o canto o percusion   yin",
                  "instrumento principal ynp",
                  "instrumentos y herramientas anal�gicas i y ii iha",
                  "instrumentos y herramientas digitales i y ii ihd",
                  "intensificaci�n agropecuaria ia",
                  "interpretaci�n de anteproyectos ian",
                  "introduc, leng. visual ylg",
                  "introduccion al portugues ipo",
                  "introducci�n a la biolog�a celular ibc",
                  "introducci�n a la comunicaci�n iac",
                  "introducci�n a la f�sica iaf",
                  "introducci�n a la programaci�n de placas ipp",
                  "introducci�n a la programaci�n orientada a objetos ioo",
                  "introducci�n a la qu�mica iaq",
                  "introducci�n a las instalaciones iai",
                  "introducci�n a las organizaciones ior",
                  "introducci�n a los sistemas constructivos isc",
                  "introducci�n al turismo y oferta tur�stica itt",
                  "investigacion social so",
                  "investigaci�n de mercados mer",
                  "investigaci�n del medio � y � a�o ime",
                  "investigaci�n operativa ope",
                  "italiano ita",
                  "kinesiologo /ki",
                  "lab. de op. unit. y tecnolog�a de los materiales lot",
                  "laboratorio de an�lisis microbiol�gicos lam",
                  "laboratorio de aplicaciones lap",
                  "laboratorio de dise�o de bases de datos ldb",
                  "laboratorio de dise�o web ldw",
                  "laboratorio de ensayo de motores ens",
                  "laboratorio de ensayos f�sicos lef",
                  "laboratorio de ensayos industriaes lei",
                  "laboratorio de hardware lhw",
                  "laboratorio de mediciones electricas lme",
                  "laboratorio de metrolog�a y control de calidad lcc",
                  "laboratorio de procesos industriales lpi",
                  "laboratorio de procesos industriales pri",
                  "laboratorio de programaci�n lpr",
                  "laboratorio de quimica organica biologica y micro qui",
                  "laboratorio de qu�mica lqi",
                  "laboratorio de qu�mica org�nica qor",
                  "laboratorio de qu�mica org�nica, biol�gica y microbiol�gica alimentos qua",
                  "laboratorio de redes inform�ticas lri",
                  "laboratorio de sistemas operativos lso",
                  "laboratorio de t�cnicas anal�ticas tec",
                  "legislaci�n laboral y liquidaci�n de haberes llh",
                  "lengua l.n",
                  "lengua extranjera -f",
                  "lengua y cultura ingles i.l",
                  "lengua y cultura portugues p.l",
                  "lengua y expresion escrita ingles i.x",
                  "lengua y expresion oral ingles i.o",
                  "lengua y literatura -b",
                  "lengua y su ense�anza l.p",
                  "lenguaje complementario artes visuales yca",
                  "lenguaje complementario danza ylz",
                  "lenguaje complementario musica ycm",
                  "lenguaje complementario teatro ylt",
                  "lenguaje complementario produc. y analisis de la imagen ylp",
                  "lenguaje de la danza led",
                  "lenguaje de la danza ydd",
                  "lenguaje musical  yen",
                  "lenguaje musical len",
                  "lenguaje musical tonal i y ii ymt",
                  "lenguaje visual i y ii yvl",
                  "lenguajes electr�nicos lee",
                  "lenguajes musicales contemporaneos ymc",
                  "lenguajes tecnol�gicos lt",
                  "lenguajes tecnol�gicos lt",
                  "lenguajes tecnol�gicos lte",
                  "lenguajes tecnol�gicos lts",
                  "linguistica l.g",
                  "literatura *a",
                  "literatura l.t",
                  "literatura lit",
                  "literatura infantil *b",
                  "logica y epistemologia l.e",
                  "logistica l.o",
                  "l�neas de transmisi�n ltr",
                  "ma-agricultura agr",
                  "ma-apicultura api",
                  "ma-avicultura avi",
                  "ma-bovinos de carne boc",
                  "ma-bovinos de leche bol",
                  "ma-cunicultura cun",
                  "ma-forrajes pof",
                  "ma-huerta hor",
                  "ma-mec�nica agr�cola meg",
                  "ma-monte frutal mof",
                  "ma-m�quinas, equipos, herramientas e inst. rurales mir",
                  "ma-ovinos ovi",
                  "ma-planta de elaboraci�n de forrajes efo",
                  "ma-porcinos pos",
                  "ma-sala de elaboraci�n de productos c�rnicos eca",
                  "ma-sala de elaboraci�n de productos l�cteos epl",
                  "ma-sala de faena sfa",
                  "ma-sala de frutas y hortlizas sfh",
                  "ma-taller rural trm",
                  "ma-vivero pvi",
                  "maest.auxiliar taller armado *ra",
                  "maest.auxiliar taller carpinteria *ca",
                  "maest.auxiliar taller confeccion *cf",
                  "maest.auxiliar taller construcciones *cn",
                  "maest.auxiliar taller huerta y granja *hg",
                  "maest.auxiliar taller marroquineria *mq",
                  "maest.auxiliar taller mecanica *tm",
                  "maest.auxiliar taller mecanografia *mn",
                  "maest.auxiliar taller servicios *ts",
                  "maest.auxiliar taller tejido *tj",
                  "maestra bibliotecaria rama adultos /mb",
                  "maestra de infantes /mi",
                  "maestra de jardin maternal /jm",
                  "maestra de pre-taller de costura /tc",
                  "maestra hospitalaria /dh",
                  "maestra iniciacion literaria escuelas de estetica mil",
                  "maestro alteraciones en el desarrollo del lenguaje /al",
                  "maestro ciegos y disminuidos visuales /dc",
                  "maestro de apoyo ma",
                  "maestro de apoyo para escuelas laborales /ab",
                  "maestro de armado /ra",
                  "maestro de articulacion /ar",
                  "maestro de ciclo /mc",
                  "maestro de danza primaria mdp",
                  "maestro de danza primaria de adultos mda",
                  "maestro de danza primaria de especial mde",
                  "maestro de discapacitados motores /dm",
                  "maestro de educacion visual inicial mvi",
                  "maestro de expresi�n corporal inicial mei",
                  "maestro de expresi�n manual primaria mmp",
                  "maestro de expresi�n pl�stica primaria mpp",
                  "maestro de expresi�n pl�stica primaria de adultos mpa",
                  "maestro de expresi�n pl�stica primaria de especial mpe",
                  "maestro de grado /mg",
                  "maestro de huerta y granja /hg",
                  "maestro de iniciacion musical-escuelas de estetica mim",
                  "maestro de irregulares mentales /im",
                  "maestro de musica-apoyo rama inicial mui",
                  "maestro de m�sica primaria mup",
                  "maestro de m�sica primaria de adultos mua",
                  "maestro de m�sica primaria de especial mue",
                  "maestro de orientacion manual /om",
                  "maestro de pre-taller de cuero /cu",
                  "maestro de pre-taller de hojalateria /ho",
                  "maestro de pre-taller de jardineria /jd",
                  "maestro de pre-taller de mantenimiento i /tu",
                  "maestro de pre-taller de mantenimiento ii /ms",
                  "maestro de pre-taller de tejido /pj",
                  "maestro de sordos e hipoacusicos /sh",
                  "maestro de taller /ta",
                  "maestro de taller de carpinteria /ca",
                  "maestro de taller de confeccion /cf",
                  "maestro de taller de construcciones /cn",
                  "maestro de taller de integracion laboral /la",
                  "maestro de taller de marroquineria /mq",
                  "maestro de taller de mecanica /tm",
                  "maestro de taller de peluqueria /pl",
                  "maestro de taller de servicios /ts",
                  "maestro de taller de tejido /tj",
                  "maestro de teatro inicial mti",
                  "maestro de teatro primaria mtp",
                  "maestro de teatro primaria de especial mte",
                  "maestro domiciliario /td",
                  "maestro educ.fisica apoyo rama especial. /ze",
                  "maestro educ.fisica para � y � ciclo egb /zp",
                  "maestro esp. int�rprete pedag. lengua se�as arg lsa",
                  "maestro especial /me",
                  "maestro especializado en grupos inicial /gi",
                  "maestro especializado en grupos primario /gp",
                  "maestro estimulador /et",
                  "maestro expresion corporal escuelas educ.estetica mec",
                  "maestro expresion dramatica escuelas educ.estetica med",
                  "maestro expresion plastica bi-dimensional mpb",
                  "maestro expresion plastica tri-dimensional mpt",
                  "maestro pretaller economia domest.y cuidados pers. /ed",
                  "maestro recuperador /mr",
                  "maestro seccion /ma",
                  "maestro severos trastornos de la personalidad /tp",
                  "mandos y automatismos mya",
                  "manifestaciones culturales mnc",
                  "mantenimiento el�ctrico mae",
                  "mantenimiento y montaje electromec�nico mme",
                  "maquillaje yaq",
                  "maquinarias agricolas/instalaciones rurales mar",
                  "maquinas el�ctricas y automatismos  mea",
                  "matematica -i",
                  "matematica m.a",
                  "matematica mtm",
                  "matematica aplicada ma",
                  "matematica aplicada a la tecnologia ma",
                  "matematica general ma",
                  "matematica y su ense�anza m.p",
                  "matem�tica - ciclo superior mcs",
                  "matem�tica aplicada map",
                  "matem�tica discreta mdi",
                  "materiales de obra mao",
                  "mecanica m.e",
                  "mec�nica mca",
                  "mec�nica agr�cola gri",
                  "mec�nica de los flu�dos mef",
                  "mec�nica de los motores endot�rmicos mmo",
                  "mec�nica y mecanismos mos",
                  "medicina m.d",
                  "mediciones equip. e instalaciones electromecanicas ele",
                  "medico clinico - medico pediatra /dd",
                  "medico especialista en rehabilitacion /si",
                  "medico neurologo /lo",
                  "medico orientador /do",
                  "medico psiquiatra /dk",
                  "medio ambiente m.b",
                  "metafisica y gnoseologia m.g",
                  "metaurgia y siderurgia mis",
                  "metodologia de la investigacion so",
                  "microbiologia m.i",
                  "microbiolog�a de los alimentos mic",
                  "modelos y sistemas mys",
                  "modelos y sistemas t.i.p.p. -o",
                  "montaje de equipos e instalaciones el�ctricas y electromec�nicas mee",
                  "montaje de proyectos electr�nicos mel",
                  "montaje e instalaci�n de circuitos el�ctricos y electr�nicos mce",
                  "montaje e instalaci�n de sistemas electr�nicos mse",
                  "montaje, operaci�n y mantenimiento de equipos e instalaciones de servicios auxiliares mox",
                  "motores de combusti�n interna mci",
                  "multimedial m.m",
                  "museologia m.u",
                  "musica amc",
                  "musica m.c",
                  "musica y movimiento yym",
                  "musica-aleman *m",
                  "musica-apreciacion *c",
                  "musica-arpa *t",
                  "musica-bandoneon *g",
                  "musica-bandoneon *t",
                  "musica-canto *k",
                  "musica-canto *j",
                  "musica-clarinete *u",
                  "musica-composicion *d",
                  "musica-contrabajo *v",
                  "musica-contrabajo *q",
                  "musica-coordinacion de conjunto *a",
                  "musica-coordinacion de conjunto *b",
                  "musica-direccion coral *i",
                  "musica-direccion coral *h",
                  "musica-direccion orquestal *j",
                  "musica-educacion musical *d",
                  "musica-educacion musical *c",
                  "musica-elementos tecnicos *f",
                  "musica-elementos tecnicos *e",
                  "musica-fagot *w",
                  "musica-fagot *r",
                  "musica-flauta *x",
                  "musica-foniatria *l",
                  "musica-foniatria *k",
                  "musica-frances *n",
                  "musica-guitarra *s",
                  "musica-guitarra *n",
                  "musica-historia i *g",
                  "musica-historia i *f",
                  "musica-historia ii *h",
                  "musica-historia ii *g",
                  "musica-ingles *p",
                  "musica-iniciacion *a",
                  "musica-italiano *o",
                  "musica-musica de camara *q",
                  "musica-musica de camara *l",
                  "musica-oboe *y",
                  "musica-percusion *l",
                  "musica-percusion *v",
                  "musica-piano *r",
                  "musica-piano *m",
                  "musica-practica de conjunto *b",
                  "musica-saxo *m",
                  "musica-saxo *w",
                  "musica-trombon *o",
                  "musica-trombon *y",
                  "musica-trompa *n",
                  "musica-trompeta *p",
                  "musica-trompeta *z",
                  "musica-viola *d",
                  "musica-viola *q",
                  "musica-violin *e",
                  "musica-violin *r",
                  "musica-violoncello *f",
                  "musica-violoncello *s",
                  "musicoterapeuta /d",
                  "m�quinas el�ctricas maq",
                  "m�quinas el�ctricas y aplicaciones mqe",
                  "m�quinas y eementos para maniobra, elevaci�n y transporte mmt",
                  "m�quinas y equipos mye",
                  "m�quinas y estructuras - montaje de equipos e instalaciones mec�nicas mem",
                  "m�canica agr�cola mag",
                  "neurologia n.e",
                  "neuropsicopatologia pq",
                  "nticx nti",
                  "nutricion n.u",
                  "nutrici�n animal nan",
                  "observatorio de comunicaci�n cultura y sociedad ocs",
                  "observatorio de medios odm",
                  "oftalmologia o.f",
                  "oleaginosas y cultivos industriales oci",
                  "op-administraci�n agraria ada",
                  "op-m�quina agr�colas mqa",
                  "op-parques y jardines pyj",
                  "op-producci�n de agroalimentos pag",
                  "op-producci�n de carnes pdc",
                  "op-producci�n de cereales, oleaginosas y cultivos industriales pco",
                  "op-producci�n de granja pdg",
                  "op-producci�n de leche pdl",
                  "op-producci�n frut�cola y forestal pff",
                  "op-producci�n hort�cola y flor�cola phf",
                  "operaciones uni. y tecnolog�a de los materiales out",
                  "operaciones unitarias y representaci�n gr�fica oug",
                  "operaci�n y mantenimiento de equipos e instalaciones el�ctricas ome",
                  "operadores y sistemas mec�nicos ops",
                  "organizacion y gestion de la produccion agrop. oga",
                  "organizaci�n de la producci�n agropecuaria apo",
                  "organizaci�n industrial oi",
                  "organizaci�n industrial y servicios ois",
                  "organizaci�n y gesti�n del trabajo y la producci�n gtp",
                  "organizaci�n y gesti�n industrial ogi",
                  "organizaci�n y m�todos oym",
                  "orientador educacional /oe",
                  "orientador educacional secundaria soe",
                  "orientador social /os",
                  "orientador social secundaria sos",
                  "ot-administraci�n agraria adt",
                  "ot-m�quinas agr�colas mqt",
                  "ot-parques y jardines pyt",
                  "ot-producciones bajo riego pbt",
                  "ot-producci�n de agroalimentos pat",
                  "ot-producci�n de carne pnt",
                  "ot-producci�n de granja pgt",
                  "ot-producci�n de leche pdt",
                  "ot-producci�n frut�cola y forestal ptt",
                  "panorama de la produccion contemporanea en danza ycd",
                  "panorama de la produccion musical contemporanea ypp",
                  "panorama de la produccion musical popular argentina y latino americana ypm",
                  "panorama de la produccion teatral ypt",
                  "patrimonio tur�stico nacional e internacional ptu",
                  "pedagogico didactica ce",
                  "percusion popular yep",
                  "periodismo p.m",
                  "perspectiva psicopedagogica de las necedidades educativas especiales intelectuales di",
                  "perspectiva psicopedagogica de las necesidades educativas especiales auditivas du",
                  "perspectiva psicopedagogica de las necesidades educativas especiales neurolocomotoras de",
                  "planeamiento pla",
                  "planeamiento y evaluaci�n de proyectos pep",
                  "planificaci�n de obra pob",
                  "plastica p.b",
                  "plastica - visual apv",
                  "plastica-administracion cultural *p",
                  "plastica-audiovisual *o",
                  "plastica-ceramica *d",
                  "plastica-ceramica ii *e",
                  "plastica-ceramica ii *k",
                  "plastica-comunicacion *k",
                  "plastica-dibujo *f",
                  "plastica-dibujo *l",
                  "plastica-dibujo ii *g",
                  "plastica-escultura *c",
                  "plastica-escultura *i",
                  "plastica-grabado *b",
                  "plastica-grabado *h",
                  "plastica-grafica *h",
                  "plastica-historia *j",
                  "plastica-historia *n",
                  "plastica-ilustracion *q",
                  "plastica-pintura *a",
                  "plastica-pintura *g",
                  "plastica-quimica *l",
                  "plastica-vision *i",
                  "plastica-vision *m",
                  "plastica-vitral *n",
                  "pol�tica y ciudadan�a pyc",
                  "portugu�s por",
                  "pp-administraci�n agraria p",
                  "pp-biotecnolog�a vegetal p",
                  "pp-parques y jardines p",
                  "pp-producciones bajo riego p",
                  "pp-producci�n de agroalimentos p",
                  "pp-producci�n de carnes p",
                  "pp-producci�n de cereales, oleaginosas y cult. ind. p",
                  "pp-producci�n de granja p",
                  "pp-producci�n de leche p",
                  "pp-producci�n frutal y forestal p",
                  "pp-turismo rural p",
                  "practica de conjuntos vocales e instrumentales yci",
                  "practica docente egb p.d",
                  "practica docente egb y polimodal ce",
                  "practica docente especial p.f",
                  "practica docente especial auditiva p.a",
                  "practica docente especial intelectual p.i",
                  "practica docente especial neurolocomotora p.n",
                  "practica docente especial visual p.v",
                  "practica docente inicial p.j",
                  "practicas del lenguaje plg",
                  "practicas turisticas tpt",
                  "preceptor /pr",
                  "preceptor pr",
                  "preceptor pra",
                  "preceptor de institutos terciarios artistica prt",
                  "preceptor de jardin maternal /pm",
                  "preceptor escuelas de estetica pee",
                  "procedimientos t�cnicos pce",
                  "procedimientos t�cnicos pcs",
                  "procedimientos t�cnicos pct",
                  "procedimientos t�cnicos pt",
                  "procedimientos t�cnicos pt",
                  "procesamiento mec�nico pmo",
                  "procesos produc.c/art ttp informatica pers.y prof. -a",
                  "procesos product. art. ttp gestion organizacional ppo",
                  "procesos productivos electrom/autom/mmo ppr",
                  "procesos productivos qu�mica ppq",
                  "procesos productivos c/art ttp electronica -t",
                  "procesos productivos c/art ttp tec. automotores -b",
                  "procesos productivos industriales ppi",
                  "procesos qu�micos y control pqc",
                  "procesos y mantenimiento industrial pmi",
                  "produc. y analisis de la imagen yai",
                  "produccion musical grupal i, ii y iii ymg",
                  "produccion radio, tv , cine p.r",
                  "producciones animales de ciclo corto pac",
                  "producciones vegetales de ciclo corto pvc",
                  "producci�n animal pan",
                  "producci�n y an�lisis de la imagen pai",
                  "producci�n y comercio exterior pre",
                  "producci�n y utilizaci�n de forrajes puf",
                  "prof. de c.e.f. /ef",
                  "prof.educ.fisica apoyo rama adultos /za",
                  "profesor danzas � ciclo egb adultos pda",
                  "profesor de danzas � ciclo egb especial pde",
                  "profesor de musica � ciclo egb especial pms",
                  "profesor de plastica � ciclo egb especial ppe",
                  "profesor de teatro � ciclo egb especial pts",
                  "profesor educ.fisica apoyo a rama inicial. /zi",
                  "profesor educ.fisica apoyo a rama psicologia /zs",
                  "profesor ingles � ciclo egb adultos +li",
                  "profesor plastica � ciclo egb adultos ppa",
                  "profesor teatro � ciclo egb adultos pta",
                  "programaci�n de circuitos prc",
                  "programaci�n orientada a objetos poo",
                  "proyecto orp",
                  "proyecto mo tecnica pt",
                  "proyecto de desarrollo de aplicaciones pds",
                  "proyecto de implementaci�n de sitios web din�micos pwd",
                  "proyecto de produccion  ydp",
                  "proyecto de produccion en artes visuales yav",
                  "proyecto de produccion en danza escenico yze",
                  "proyecto de produccion en danza ypd",
                  "proyecto de produccion en teatro popular yta",
                  "proyecto de producci�n en artes visuales pav",
                  "proyecto de producci�n en danza ppd",
                  "proyecto de producci�n en literatura ppl",
                  "proyecto de producci�n en m�sica ppm",
                  "proyecto de producci�n en teatro ppt",
                  "proyecto final prf",
                  "proyecto integrador m.m.o. -a",
                  "proyecto integrador mmo pit",
                  "proyecto tecnica pt",
                  "proyecto y dise�o electromecanico t.e.i.e. -r",
                  "proyecto y dise�o electromec�nico pdn",
                  "proyecto y dise�o electronico t.e. -h",
                  "proyecto y dise�o electr�nico pye",
                  "proyecto y producci�n electrom/autom prn",
                  "proyecto y producci�n inform�tica ppu",
                  "proyecto y producci�n mmo pyy",
                  "proyectos de artistica par",
                  "proyectos de educacion agraria pea",
                  "proyectos de instalaciones pin",
                  "proyectos de investigaci�n en ciencias sociales pic",
                  "proyectos organizacionales pro",
                  "proyectos y produc.c/art ttp maestro mayor de obra -g",
                  "proyectos y produccion c/art ttp electronica -r",
                  "pr�cticas corporales y dep en el ambiente natural pcd",
                  "pr�cticas de conjuntos vocales e instrumentales pci",
                  "pr�cticas deportivas y acu�ticas pdo",
                  "pr�cticas deportivas y atl�ticas pdi",
                  "pr�cticas deportivas y juegos pdj",
                  "pr�cticas gimn�sticas y expresivas pge",
                  "psicologia *a",
                  "psicologia -r",
                  "psicologia p.s",
                  "psicologia ii *b",
                  "psicologia social p.c",
                  "psicologia social del turismo sst",
                  "psicologia social e institucional pc",
                  "psicologo /po",
                  "psicolog�a psi",
                  "psicopatologia pq",
                  "psicopedagogia p.p",
                  "publicidad p.u",
                  "puesta en escena yee",
                  "quimica q.u",
                  "quimica qmc",
                  "quimica profesorados q.p",
                  "quimica y su ense�anza q.e",
                  "qu�mica anal�tica qan",
                  "qu�mica del carbono qdc",
                  "qu�mica general e inorg�nica qgi",
                  "qu�mica industrial qi",
                  "qu�mica org�nica qo",
                  "qu�mica org�nica biol�gica qob",
                  "qu�mica org�nica y biol�gica alim qoa",
                  "radio r.a",
                  "rectificaci�n de motores rmo",
                  "recursos humanos r.h",
                  "recursos ling��sticos rli",
                  "relaciones p�blicas protocolo y ceremonial rpp",
                  "representaci�n gr�fica electrom/autom rgg",
                  "resistencia de materiaes y c�culo de eementos de m�quina rma",
                  "resistencia y ensayos de los materiales rem",
                  "salud s.a",
                  "salud y adolescencia sya",
                  "secretario xxs",
                  "seguridad e higiene s.h",
                  "seguridad inform�tica ins",
                  "seminario de accesibilidad turistica sat",
                  "seminario de investigaci�n literaria sil",
                  "seminario turismo y sustentabilidad sty",
                  "semiotica s.e",
                  "servicios tur�sticos stu",
                  "sistemas autotr�nicos sa",
                  "sistemas constructivos  i  -  ii sct",
                  "sistemas constructivos sco",
                  "sistemas de comunicaciones sc",
                  "sistemas de gesti�n y autogesti�n sga",
                  "sistemas de informaci�n contable sic",
                  "sistemas de informaci�n contable i,  ii,  iii sin",
                  "sistemas de inyecci�n si",
                  "sistemas de suspensi�n direcci�n y frenos ss",
                  "sistemas de transmisi�n str",
                  "sistemas digitales sd",
                  "sistemas electricos y electronicos aplicados ttp -y",
                  "sistemas el�ctricos y electr�nicos aplicados see",
                  "sistemas hidr�ulicos y neum�ticos shn",
                  "sistemas mec�nicos sm",
                  "sistemas productivos sp",
                  "sistemas tecnol�gicos st",
                  "sistemas tecnol�gicos st",
                  "sistemas tecnol�gicos st",
                  "sistemas tecnol�gicos st",
                  "sistemas tecnol�gicos sts",
                  "sociologia *c",
                  "sociologia s.o",
                  "sociolog�a soc",
                  "taller artes audiovisuales yaa",
                  "taller de composicion  ydc",
                  "taller de comunicaci�n institucional y comunitaria tci",
                  "taller de escritura tde",
                  "taller de literatura y escritura tle",
                  "taller de mejora y optimizaci�n de las producciones tmp",
                  "taller de mimo ydm",
                  "taller de percusion  ytn",
                  "taller de prod. bidimen. ypb",
                  "taller de prod. tridimen. yty",
                  "taller de produc. en dibujo e ilustracion  yti",
                  "taller de produc. en grabado y arte impreso yga",
                  "taller de produc. en pintura ytp",
                  "taller de produc. escultura y ceramica o arte del fuego yar",
                  "taller de produccion literaria ypl",
                  "taller de producci�n en lenguajes ocl",
                  "taller rural tru",
                  "teatro *a",
                  "teatro *b",
                  "teatro att",
                  "teatro yte",
                  "teatro escenografia *c",
                  "teatro popular practica escenica en teatro callejero ytc",
                  "teatro-historia *f",
                  "teatro-maquillaje *d",
                  "tecnico docente medico tdm",
                  "tecnol.de los mat./art ttp informatica per.y prof -l",
                  "tecnolog. electr�nicas t�c.inform�t.prof.y pers. tee",
                  "tecnolog.de cont. c/art ttp equip.e inst. electrom -o",
                  "tecnologia de cont. c/art ttp electronica -q",
                  "tecnologia de gestion c/art ttp electronica -t",
                  "tecnologias de la informacion y la comunicacion -z",
                  "tecnolog�a de gesti�n electrom/autom/mmo tgm",
                  "tecnolog�a de gesti�n electr�nica tgs",
                  "tecnolog�a de gesti�n gest. org. tga",
                  "tecnolog�a de la informaci�n tur�stica tit",
                  "tecnolog�a de los materiales mmo tmo",
                  "tecnolog�a electr�nica t�cnico en electr�nica tel",
                  "tecnolog�a el�ctrica tet",
                  "tecnolog�a mec�nica tem",
                  "tecnolog�as de control electr�nica/inform�tica/mmo tct",
                  "tecnolog�as de la informaci�n de la gesti�n tig",
                  "tecnolog�as de la informaci�n y la comunicaci�n tic",
                  "teleinform�tica tli",
                  "teoria del turismo ttt",
                  "teoria e historia de los procesos artisticos i, ii, iii y iv ypa",
                  "teor�a de las organizaciones gest. org. tor",
                  "teor�a de las organizaciones tdo",
                  "teor�a y t�cnica impositiva tti",
                  "terapista ocupacional /to",
                  "termodin�mica tdn",
                  "termodin�mica y m�quinas t�rmicas tmt",
                  "textil indumentaria t.i",
                  "trabajo corporal yrc",
                  "trabajo social t.s",
                  "trabajo y ciudadan�a tyc",
                  "turismo t.u",
                  "t�cnicas de diagn�stico ted",
                  "uni�n y conformaci�n de os materiales uyc",
                  "verano atr - artistica vpa",
                  "verano atr - educacion fisica vef",
                  "verano atr - guardavida vgu",
                  "verano atr - perfil general vpg",
                  "verano c.e. artistica cea",
                  "verano c.e. educacion fisica cef",
                  "verano c.e. lengua cel",
                  "verano c.e. maestros especial cee",
                  "verano c.e. maestros primaria cep",
                  "verano c.e. matematica cem",
                  "verificaci�n y mantenimiento el�ctricol autom�vil vma",
                  "veterinaria v.e",
                  "vicedirector xvd",
                  "vivero vvr",
                  "� producciones florales, ornamentales, frutales y forestales fff"]
          